// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

type Service struct {
	ID         int64  `json:"id"`
	Title      string `json:"title"`
	Url        string `json:"url"`
	IconPath   string `json:"icon_path"`
	OpenNewTab int64  `json:"open_new_tab"`
	Position   int64  `json:"position"`
}

type Session struct {
	Token     string `json:"token"`
	UserID    int64  `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type User struct {
	ID           int64  `json:"id"`
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}
