// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package db

import (
	"context"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS count FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO services (title, url, icon_path, open_new_tab, position)
VALUES (?, ?, ?, ?, ?)
RETURNING id, title, url, icon_path, open_new_tab, position
`

type CreateServiceParams struct {
	Title      string `json:"title"`
	Url        string `json:"url"`
	IconPath   string `json:"icon_path"`
	OpenNewTab int64  `json:"open_new_tab"`
	Position   int64  `json:"position"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (Service, error) {
	row := q.db.QueryRowContext(ctx, createService,
		arg.Title,
		arg.Url,
		arg.IconPath,
		arg.OpenNewTab,
		arg.Position,
	)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.IconPath,
		&i.OpenNewTab,
		&i.Position,
	)
	return i, err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token, user_id, expires_at) VALUES (?, ?, ?)
`

type CreateSessionParams struct {
	Token     string `json:"token"`
	UserID    int64  `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.ExecContext(ctx, createSession, arg.Token, arg.UserID, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, password_hash) VALUES (?, ?)
RETURNING id, username, password_hash
`

type CreateUserParams struct {
	Username     string `json:"username"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser, arg.Username, arg.PasswordHash)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiresAt int64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiresAt)
	return err
}

const deleteService = `-- name: DeleteService :exec
DELETE FROM services WHERE id = ?
`

func (q *Queries) DeleteService(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteService, id)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getService = `-- name: GetService :one
SELECT id, title, url, icon_path, open_new_tab, position
FROM services
WHERE id = ?
`

func (q *Queries) GetService(ctx context.Context, id int64) (Service, error) {
	row := q.db.QueryRowContext(ctx, getService, id)
	var i Service
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Url,
		&i.IconPath,
		&i.OpenNewTab,
		&i.Position,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT s.token, s.user_id, s.expires_at, u.username
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token = ?
`

type GetSessionRow struct {
	Token     string `json:"token"`
	UserID    int64  `json:"user_id"`
	ExpiresAt int64  `json:"expires_at"`
	Username  string `json:"username"`
}

func (q *Queries) GetSession(ctx context.Context, token string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i GetSessionRow
	err := row.Scan(
		&i.Token,
		&i.UserID,
		&i.ExpiresAt,
		&i.Username,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = ?
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRowContext(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, password_hash FROM users WHERE username = ?
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(&i.ID, &i.Username, &i.PasswordHash)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, title, url, icon_path, open_new_tab, position
FROM services
ORDER BY position ASC, id ASC
`

func (q *Queries) ListServices(ctx context.Context) ([]Service, error) {
	rows, err := q.db.QueryContext(ctx, listServices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Service{}
	for rows.Next() {
		var i Service
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Url,
			&i.IconPath,
			&i.OpenNewTab,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxServicePosition = `-- name: MaxServicePosition :one
SELECT CAST(COALESCE(MAX(position), -1) AS INTEGER) AS max_position FROM services
`

func (q *Queries) MaxServicePosition(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxServicePosition)
	var max_position int64
	err := row.Scan(&max_position)
	return max_position, err
}

const refreshSession = `-- name: RefreshSession :exec
UPDATE sessions SET expires_at = ? WHERE token = ?
`

type RefreshSessionParams struct {
	ExpiresAt int64  `json:"expires_at"`
	Token     string `json:"token"`
}

func (q *Queries) RefreshSession(ctx context.Context, arg RefreshSessionParams) error {
	_, err := q.db.ExecContext(ctx, refreshSession, arg.ExpiresAt, arg.Token)
	return err
}

const setServiceIconPath = `-- name: SetServiceIconPath :exec
UPDATE services SET icon_path = ? WHERE id = ?
`

type SetServiceIconPathParams struct {
	IconPath string `json:"icon_path"`
	ID       int64  `json:"id"`
}

func (q *Queries) SetServiceIconPath(ctx context.Context, arg SetServiceIconPathParams) error {
	_, err := q.db.ExecContext(ctx, setServiceIconPath, arg.IconPath, arg.ID)
	return err
}

const setServicePosition = `-- name: SetServicePosition :exec
UPDATE services SET position = ? WHERE id = ?
`

type SetServicePositionParams struct {
	Position int64 `json:"position"`
	ID       int64 `json:"id"`
}

func (q *Queries) SetServicePosition(ctx context.Context, arg SetServicePositionParams) error {
	_, err := q.db.ExecContext(ctx, setServicePosition, arg.Position, arg.ID)
	return err
}

const updateService = `-- name: UpdateService :exec
UPDATE services
SET title = ?, url = ?, open_new_tab = ?
WHERE id = ?
`

type UpdateServiceParams struct {
	Title      string `json:"title"`
	Url        string `json:"url"`
	OpenNewTab int64  `json:"open_new_tab"`
	ID         int64  `json:"id"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) error {
	_, err := q.db.ExecContext(ctx, updateService,
		arg.Title,
		arg.Url,
		arg.OpenNewTab,
		arg.ID,
	)
	return err
}

const upsertSetting = `-- name: UpsertSetting :exec
INSERT INTO settings (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertSettingParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpsertSetting(ctx context.Context, arg UpsertSettingParams) error {
	_, err := q.db.ExecContext(ctx, upsertSetting, arg.Key, arg.Value)
	return err
}
